FROM ontouchstart/julia-base
MAINTAINER Sam Liu <ontouchstart@gmail.com>

RUN git clone https://github.com/ontouchstart/julia.git
RUN cd julia && make LLVM_CONFIG=llvm-config-3.3 USE_BLAS64=0 USE_SYSTEM_LLVM=1 USE_SYSTEM_ZLIB=1 USE_SYSTEM_SUITESPARSE=1 USE_SYSTEM_ARPACK=1 USE_SYSTEM_BLAS=1 USE_SYSTEM_FFTW=1 USE_SYSTEM_LAPACK=1 USE_SYSTEM_GMP=1 USE_SYSTEM_MPFR=1 USE_SYSTEM_PCRE=1 USE_SYSTEM_LIBUNWIND=1 USE_SYSTEM_READLINE=1 USE_SYSTEM_GRISU=1 USE_SYSTEM_OPENLIBM=1 USE_SYSTEM_RMATH=1
VOLUME ["/data"]
ENTRYPOINT ["/julia/julia"] 
